name: Generate Datas

on:
  schedule: # execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: gleenout
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Atualizado para Node.js 16

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.2.0 # Atualizado para a versão mais recente
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
